name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    name: Run PR Agent on PR
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OCR_LLM_TOKEN }}
          OPENAI_API_BASE: "https://integrate.api.nvidia.com/v1"
          CONFIG__MODEL: "openai/qwen/qwen2.5-coder-32b-instruct"
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: "65536"
          CONFIG__PR_ACTIONS: '["opened", "reopened", "ready_for_review", "synchronize"]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
